# Generated by Django 4.2.5 on 2023-09-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='devis',
            new_name='devi',
        ),
        migrations.RenameModel(
            old_name='emails',
            new_name='email',
        ),
    ]
