# Generated by Django 4.2.5 on 2023-09-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0004_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloc',
            name='id',
        ),
        migrations.AlterField(
            model_name='bloc',
            name='letter',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
    ]
