# Generated by Django 4.2.5 on 2023-09-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0005_remove_bloc_id_alter_bloc_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloc',
            name='etat',
            field=models.TextField(default='Travaux pas entamés', max_length=1500),
        ),
    ]
