# Generated by Django 4.2.5 on 2023-09-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spi', '0007_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devi',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='devi',
            name='type_appart',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
